# Generated by Django 4.1.4 on 2023-01-27 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('user_address', models.TextField(blank=True, max_length=150, null=True)),
                ('user_age', models.CharField(blank=True, max_length=2, null=True)),
                ('user_gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user_profile_pic', models.ImageField(default='profile_pic/avtar_2x', null=True, upload_to='Profile_pic/user_p')),
            ],
        ),
    ]
