# Generated by Django 4.1.4 on 2023-01-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_profile_pic',
            field=models.ImageField(default='vendor_p/avtar_2x', null=True, upload_to='user_p'),
        ),
    ]
