# Generated by Django 4.1.4 on 2023-01-29 11:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_profile_model_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='user_profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='user_p/avatar_2x.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[450, 450], upload_to='Profile_pic'),
        ),
    ]
