# Generated by Django 4.1.4 on 2023-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='static/media/Vendor')),
                ('company_name', models.CharField(max_length=150, null=True)),
                ('vendor_address', models.TextField(max_length=100, null=True)),
                ('vendor_contact', models.CharField(max_length=10, null=True)),
                ('product_category', models.CharField(choices=[('', 'Select Your Category'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dry-Fruits', 'Dry-Fruits'), ('Beverages', 'Beverages')], max_length=100, null=True)),
                ('MFG_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('piece', models.IntegerField(null=True)),
                ('product_old_price', models.IntegerField(null=True)),
            ],
        ),
    ]
