# Generated by Django 4.1.4 on 2023-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
    ]
