# Generated by Django 4.1.4 on 2023-01-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_mfg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='vendor_address',
        ),
        migrations.RemoveField(
            model_name='products',
            name='vendor_contact',
        ),
    ]
