# Generated by Django 4.1.4 on 2023-01-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_vendor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='company_name',
        ),
    ]
