# Generated by Django 4.1.4 on 2023-01-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0016_alter_vendor_profile_model_profile_pic'),
        ('products', '0008_remove_products_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Vendor.vendor_profile_model'),
            preserve_default=False,
        ),
    ]
