# Generated by Django 4.1.4 on 2023-01-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0022_alter_vendor_profile_model_profile_pic_and_more'),
        ('products', '0011_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Vendor.vendor_profile_model'),
        ),
    ]
