# Generated by Django 4.1.4 on 2023-01-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='MFG_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
