# Generated by Django 4.1.4 on 2023-02-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0025_vendor_profile_model_id_and_more'),
        ('products', '0015_alter_products_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Vendor.vendor_profile_model'),
            preserve_default=False,
        ),
    ]
