# Generated by Django 4.1.4 on 2023-02-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0025_vendor_profile_model_id_and_more'),
        ('products', '0016_products_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Vendor.vendor_profile_model'),
        ),
    ]
