# Generated by Django 4.1.4 on 2023-02-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_products_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='company_name',
        ),
    ]
